"""Create Transaction Table

Revision ID: 9832c9e974b7
Revises: 
Create Date: 2020-10-03 21:11:17.800083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9832c9e974b7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ItemID", sa.String(), nullable=True),
        sa.Column("LocationId", sa.String(), nullable=True),
        sa.Column("TransactionDate", sa.Date(), nullable=True),
        sa.Column("TransferQuantity", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    # ### end Alembic commands ###
